### PR TITLE
Some general cleanup and OKH fixes

### PR DESCRIPTION
**Pull request by hoijui**
If you have doubts about the last commit (cleaning up markdown),
I am happy to remove it form this PR.

### CODE REVIEW

**Comment by hoijui** [comment]
Btw... we'll have a big event now in the beginning of March in Hamburg, in case you are living close to there... I would tell you more.

**Comment by KarlK90** [comment]
> Btw... we'll have a big event now in the beginning of March in Hamburg, in case you are living close to there... I would tell you more.

@hoijui I haven't seen your PR, I should really setup notifications. I'll go through it tomorrow. For the invitation - I'm Leipzig based so Hamburg is sadly not right around the corner...

**Comment by hoijui** [comment]
ahhh I see .. Are you somehow connected to the Kanthaus, maybe?

I am at the event right now! in some tiny part, your project is involved too, as one of the indexed projects (thanks to OKH) that are available through an experimental, alternative kind of .. economic system for fab-labs and OSH... roughly speaking.
... thanks! :-)

... and I am still hoping to get to build it myself some day .. maybe this year, with more free time.

**Review by KarlK90 — APPROVED** [review]
It took more time as expected to look at these changes. They look good to me, thank you for the cleanup.

**Comment by KarlK90** [comment]
> ahhh I see .. Are you somehow connected to the Kanthaus, maybe?

I haven't heard of them before you mentioned them actually. But looks like a cool project!

> I am at the event right now! in some tiny part, your project is involved too, as one of the indexed projects (thanks to OKH) that are available through an experimental, alternative kind of .. economic system for fab-labs and OSH... roughly speaking. ... thanks! :-)

That is cool, hope you had a great time there!

> ... and I am still hoping to get to build it myself some day .. maybe this year, with more free time.

Fingers crossed :crossed_fingers: that you'll make it :slightly_smiling_face:

**Pull request merged**
